version: '3.7'

services:
        gcloud:
                image: 'gcr.io/cloud-builders/gcloud:latest'
                volumes:
                  - type: bind
                    source: .
                    target: /
                entrypoint: ''
