version: '3.7'

services:
        gcloud:
                image: 'gcr.io/cloud-builders/gcloud-slim:latest'
                volumes:
                  - type: bind
                    source: .
                    target: /pipeline
                entrypoint: /pipeline/entrypoint.sh
