trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadSecureFile@1
  name: sakey
  displayName: Download SA
  inputs:
    secureFile: sa-key.json

- script: cp $(sakey.secureFilePath) ./sa-key.json
  displayName: 'Copy the sa-key.json'

- script: |
    ls
    chmod +x *.sh
    
  displayName: 'List contents'

- task: DockerCompose@0
  displayName: Apply the Folders config
  inputs:
    containerregistrytype: 'Container Registry'
    dockerComposeFile: 'docker-compose.yaml'
    dockerRegistryEndpoint: 'GCR'
    action: 'Run a specific service'
    serviceName: 'gcloud'
    containerCommand: /pipeline/dm.sh
    # containerCommand: cat /pipeline/sa-key.json 
    detached: false