trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadSecureFile@1
  name: sakey
  displayName: Download Service Account keyfile
  inputs:
    secureFile: sa-key.json

- script: cp $(sakey.secureFilePath) ./sa-key.json
  displayName: 'Copy Service Account Keyfile'

- script: |
    ls
    chmod +x *.sh
    
  displayName: Prepare working directory

- task: DockerCompose@0
  displayName: Apply the Folders config
  inputs:
    containerregistrytype: 'Container Registry'
    dockerComposeFile: 'docker-compose.yaml'
    dockerRegistryEndpoint: 'GCR'
    action: 'Run a specific service'
    serviceName: 'gcloud'
    containerCommand: /pipeline/dm.sh
    detached: false
    dockerComposeFileArgs: |
      ORGANIZATION=279306703376
      DM_PROJECT=premium-modem-261922